server:
  port: 7002
eureka:
  instance:
    hostname: jichi-eureka-7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://jichi-eureka-7001.com:7001/eureka/
